"use client";

import { useState, useTransition } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "./ui/button";
import { FileClock, LoaderCircle } from "lucide-react";
import Popup from "./Popup";
import {
  Form,
  FormField,
  FormItem,
  FormLabel,
  FormControl,
  FormMessage,
} from "./ui/form";
import { Input } from "./ui/input";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from "./ui/card";
import { uploadFundraiser } from "@/app/actions/fundraiser";
import DatePicker from "./DatePicker";

const formSchema = z.object({
  title: z.string().max(40, "Title cannot be more than 40 characters long."),
  amount: z.coerce
    .number()
    .min(0.01, "Amount of money must be greater than $0.00"),
  time: z.string(),
  date: z.date(),
});

export default function FundraiserForm() {
  const [showPopup, setShowPopup] = useState(false);
  const [popupTitle, setPopupTitle] = useState("");
  const [popupDescription, setPopupDescription] = useState("");
  const [loading, startTransition] = useTransition();

  const form = useForm({
    resolver: zodResolver(formSchema),
    mode: "onChange",
    defaultValues: {
      title: "",
      amount: 0,
      time: "",
      date: new Date(),
    },
  });

  function createPopup(title: string, description: string) {
    setPopupTitle(title);
    setPopupDescription(description);
    setShowPopup(true);
  }

  async function onSubmit(values: {
    amount: number;
    title: string;
    time: string;
  }) {
    const formData = new FormData();
    formData.append("amount", values.amount.toString());
    formData.append("title", values.title);
    formData.append("time", values.time);

    startTransition(async () => {
      const res = await uploadFundraiser(formData);
      if (!res.ok) {
        createPopup(
          "500: Internal Server Error",
          res.error || "An error occurred logging your fundraiser."
        );
      }
    });
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Log new fundraiser</CardTitle>
        <CardDescription>
          Track the profits generated by fundraisers, donations, and deposits.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(onSubmit)}
            className="flex flex-col gap-6"
          >
            <FormField
              control={form.control}
              name="title"
              render={({ field }) => (
                <FormItem className="space-y-1">
                  <FormLabel htmlFor="title">Title</FormLabel>
                  <FormControl>
                    <Input
                      id="title"
                      type="text"
                      disabled={loading}
                      placeholder="Title of the fundraiser"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="amount"
              render={({ field }) => (
                <FormItem className="space-y-1">
                  <FormLabel htmlFor="amount">Amount of money</FormLabel>
                  <FormControl>
                    <Input
                      id="amount"
                      type="number"
                      min={0.0}
                      step={0.01}
                      disabled={loading}
                      placeholder="0.00"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="date"
              render={({ field: dateField }) => (
                <FormField
                  control={form.control}
                  name="time"
                  render={({ field: timeField }) => (
                    <FormItem className="space-y-1">
                      <FormControl>
                        <DatePicker
                          date={dateField.value}
                          time={timeField.value}
                          onDateChange={dateField.onChange}
                          onTimeChange={timeField.onChange}
                          disabled={loading}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              )}
            />
            <Button
              type="submit"
              className="w-full hover:cursor-pointer"
              disabled={loading}
              variant="outline"
            >
              {loading ? (
                <LoaderCircle className="animate-spin" />
              ) : (
                <FileClock />
              )}
              {loading ? "Logging..." : "Log fundraiser"}
            </Button>
          </form>
        </Form>
        {showPopup && (
          <Popup
            title={popupTitle}
            description={popupDescription}
            onClose={() => setShowPopup(false)}
          />
        )}
      </CardContent>
    </Card>
  );
}
